export function getFormOptions(t) {
  return {
    country: [
      ['', t('formOptions.selectPlaceholder')],
      ['Argentina', 'Argentina'],
      ['Brasil', 'Brasil'],
      ['Chile', 'Chile'],
      ['Uruguay', 'Uruguay'],
      ['Paraguay', 'Paraguay'],
      ['Bolivia', 'Bolivia'],
      ['Perú', 'Perú'],
      ['Colombia', 'Colombia'],
      ['Ecuador', 'Ecuador'],
      ['Venezuela', 'Venezuela'],
      ['México', 'México'],
      ['Estados Unidos', t('formOptions.country.unitedStates')],
      ['Canadá', t('formOptions.country.canada')],
      ['España', t('formOptions.country.spain')],
      ['Reino Unido', t('formOptions.country.unitedKingdom')],
      ['Francia', t('formOptions.country.france')],
      ['Alemania', t('formOptions.country.germany')],
      ['Italia', t('formOptions.country.italy')],
      ['Portugal', t('formOptions.country.portugal')],
      ['Polonia', t('formOptions.country.poland')],
      ['Ucrania', t('formOptions.country.ukraine')],
      ['Rusia', t('formOptions.country.russia')],
      ['Turquía', t('formOptions.country.turkey')],
      ['Sudáfrica', t('formOptions.country.southAfrica')],
      ['Australia', t('formOptions.country.australia')],
      ['Nueva Zelanda', t('formOptions.country.newZealand')],
      ['Japón', t('formOptions.country.japan')],
      ['China', t('formOptions.country.china')],
      ['India', t('formOptions.country.india')],
    ],
    sex: [
      ['', t('formOptions.selectPlaceholder')],
      ['Masculino', t('formOptions.sex.male')],
      ['Femenino', t('formOptions.sex.female')],
    ],
    division: ['Open', 'Youth', 'Junior', 'Sub-Masters', 'Masters'],
    category: ['Raw', 'Raw With Wraps', 'Single-Ply', 'Multi-Ply', 'Unlimited'],
    paymentMethod: [
      ['mercado_pago', t('formOptions.payment.mercadoPago')],
      ['manual_link', t('formOptions.payment.manualLink')],
      ['cash_pitbull', t('formOptions.payment.cashPitbull')],
    ],
  }
}
