// Ambient export declarations for design-sync (claude.ai/design) component
// discovery. This app ships no TypeScript; design-sync's converter needs a
// .d.ts export list to match Storybook titles to real components — the
// runtime source of truth stays .design-sync/entry.js.
export declare function AboutSection(props: any): any
export declare function AuditTimeline(props: any): any
export declare function BrandLogo(props: any): any
export declare function Button(props: any): any
export declare function CTASection(props: any): any
export declare function CapacityBar(props: any): any
export declare function CardPreviewModal(props: any): any
export declare function BenefitCard(props: any): any
export declare function PricingCard(props: any): any
export declare function InfoCard(props: any): any
export declare function CommunitySpotlight(props: any): any
export declare function ContactForm(props: any): any
export declare function DataTable(props: any): any
export declare function DigitalCredential(props: any): any
export declare function EmptyState(props: any): any
export declare function ErrorState(props: any): any
export declare function EventCalendar(props: any): any
export declare function EventCard(props: any): any
export declare function EventLiveStream(props: any): any
export declare function EventShareCard(props: any): any
export declare function ExportButton(props: any): any
export declare function FAQAccordion(props: any): any
export declare function FilterPills(props: any): any
export declare function Field(props: any): any
export declare function Select(props: any): any
export declare function FormSection(props: any): any
export declare function HeroStatusCard(props: any): any
export declare function HomeMembershipBand(props: any): any
export declare function HomeQuickBand(props: any): any
export declare function HomeResultsTeaser(props: any): any
export declare function HomeRulebookTeaser(props: any): any
export declare function LanguageToggle(props: any): any
export declare function LoadingState(props: any): any
export declare function FlagAr(props: any): any
export declare function FlagUs(props: any): any
export declare function LoginButton(props: any): any
export declare function MemberProfileCard(props: any): any
export declare function MembersHeroRail(props: any): any
export declare function MembershipCard(props: any): any
export declare function PaymentStatusCard(props: any): any
export declare function PitbullFeatureVisual(props: any): any
export declare function PitbullSpotlight(props: any): any
export declare function PlatformMap(props: any): any
export declare function Podium(props: any): any
export declare function ResultCard(props: any): any
export declare function ResultsArchiveList(props: any): any
export declare function ResultsArchiveToolbar(props: any): any
export declare function ResultsEventPanel(props: any): any
export declare function ResultsSortMenu(props: any): any
export declare function Reveal(props: any): any
export declare function SectionHeading(props: any): any
export declare function SegmentedSwitch(props: any): any
export declare function SpotlightCard(props: any): any
export declare function StaggerReveal(props: any): any
export declare function StatBlock(props: any): any
export declare function StatusPill(props: any): any
export declare function SubNav(props: any): any
export declare function ThemeToggle(props: any): any
export declare function TicketPurchaseSection(props: any): any
export declare function TrustStrip(props: any): any
export declare function AdminShell(props: any): any
export declare function AdminTopBar(props: any): any
export declare function DesignPageHero(props: any): any
export declare function Footer(props: any): any
export declare function HeroSection(props: any): any
export declare function NavbarPublic(props: any): any
export declare function PageFrame(props: any): any
export declare function PageTransition(props: any): any
export declare function ThemeProvider(props: any): any
export declare function I18nProvider(props: any): any
export declare function OAuthProvider(props: any): any
